### PR TITLE
Add LICENSE

### LINKED ISSUE #9: Add a License
@ian-r-rose , how would you like to handle this?

### PR DESCRIPTION
**Pull request by mrocklin**
Fixes #9

### CODE REVIEW

**Comment by ian-r-rose** [comment]
Looks good to me. Can we also add 
`license": "BSD-3-Clause",`
to the `package.json`?

**Comment by mrocklin** [comment]
Already there it seems

**Comment by mrocklin** [comment]
https://github.com/ian-r-rose/jupyterlab-bokeh-server/blob/ca2e1ddf441f83e97226abb3acbf2c3ba8a0d471/package.json#L14

**Comment by ian-r-rose** [comment]
Ah, right :)

**Pull request merged**
